# Generated by Django 4.2.16 on 2025-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شهر"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="experience",
            field=models.IntegerField(default=0, verbose_name="سابقه کار (سال)"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=3, verbose_name="امتیاز"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="specialty",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="تخصص"
            ),
        ),
    ]
