# Generated by Django 4.2.16 on 2025-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_customuser_bio_customuser_city_customuser_experience_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name_fa",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="نام (فارسی)"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name_fa",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="نام خانوادگی (فارسی)",
            ),
        ),
    ]
