# Generated by Django 4.2.16 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_first_name_fa_customuser_last_name_fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="عکس پروفایل",
            ),
        ),
    ]
