# Generated by Django 4.2.16 on 2025-11-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="awards",
            field=models.TextField(
                blank=True, null=True, verbose_name="جوایز و افتخارات"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="certifications",
            field=models.TextField(
                blank=True, null=True, verbose_name="گواهینامه\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="education",
            field=models.TextField(blank=True, null=True, verbose_name="تحصیلات"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="زبان\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="publications",
            field=models.TextField(
                blank=True, null=True, verbose_name="مقالات و انتشارات"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="research_interests",
            field=models.TextField(blank=True, null=True, verbose_name="علایق پژوهشی"),
        ),
    ]
