# Generated by Django 4.2.16 on 2025-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_awards_customuser_certifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name_fa",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name_fa",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
