# Generated by Django 4.2.16 on 2025-12-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_first_name_fa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار تایید"),
                    ("approved", "تایید شده"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت تایید",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تایید"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تایید شده توسط",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True, verbose_name="دلیل رد"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="requested_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ درخواست"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="فعال"),
        ),
    ]
