# Generated by Django 4.2.16 on 2025-11-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="اسلاگ"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "کنفرانس"),
                            ("workshop", "کارگاه"),
                            ("seminar", "سمینار"),
                            ("congress", "کنگره"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/", verbose_name="تصویر"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="مکان")),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مهلت ثبت نام"
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حداکثر شرکت\u200cکننده"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="تعداد بازدید")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد",
                "verbose_name_plural": "رویدادها",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت نام"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="یادداشت"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="رویداد",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت نام رویداد",
                "verbose_name_plural": "ثبت نام\u200cهای رویداد",
                "ordering": ["-registered_at"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
