# Generated by Django 4.2.16 on 2025-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="agenda",
            field=models.TextField(blank=True, null=True, verbose_name="برنامه زمانی"),
        ),
        migrations.AddField(
            model_name="event",
            name="contact_info",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="اطلاعات تماس"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/covers/",
                verbose_name="تصویر کاور",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "فروردین"),
                    (2, "اردیبهشت"),
                    (3, "خرداد"),
                    (4, "تیر"),
                    (5, "مرداد"),
                    (6, "شهریور"),
                    (7, "مهر"),
                    (8, "آبان"),
                    (9, "آذر"),
                    (10, "دی"),
                    (11, "بهمن"),
                    (12, "اسفند"),
                ],
                null=True,
                verbose_name="ماه رویداد",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="سال رویداد"),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="برگزارکننده"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="prerequisites",
            field=models.TextField(
                blank=True, null=True, verbose_name="پیش\u200cنیازها"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="خلاصه توضیحات"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="speakers",
            field=models.TextField(blank=True, null=True, verbose_name="سخنرانان"),
        ),
        migrations.AddField(
            model_name="event",
            name="target_audience",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="مخاطبان"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="events/", verbose_name="تصویر (قدیمی)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="منتشر شده"),
        ),
    ]
