# Generated by Django 4.2.16 on 2025-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_agenda_event_contact_info_event_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-event_year", "-event_month"],
                "verbose_name": "رویداد",
                "verbose_name_plural": "رویدادها",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateField(blank=True, null=True, verbose_name="مهلت ثبت نام"),
        ),
    ]
