# Generated by Django 4.2.16 on 2025-11-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="اسلاگ"),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="تصویر"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="تعداد بازدید")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="اسلاگ"),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="announcements/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="مهم"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="تعداد بازدید")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعیه",
                "verbose_name_plural": "اطلاعیه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
