# Generated by Django 4.2.16 on 2025-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="دسته\u200cبندی"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="short_content",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="خلاصه خبر"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="source",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="منبع"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="برچسب\u200cها (جدا شده با کاما)",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="منتشر شده"),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="منتشر شده"),
        ),
    ]
